### ISSUE TITLE
Maybe put the wrappers into different repositories?

### ISSUE THREAD

**Issue by neroist** [webui-dev/webui#100]
For organizational reasons and the fact the wrappers look odd being placed into the "examples" directory, perhaps put them into different repositories?

**Comment by AlbertShown** [comment]
I 100% agree !

**Comment by hassandraga** [comment]
@neroist, @AlbertShown, @malisipi.

I was thinking about this idea before, but I wasn't sure. Now you bring this up, so I'm thinking about creating a new organization dedicated to the WebUI. Then we move all those repositories to the new organization (_its issues, pull requests, wiki, stars, and watchers are also transferred_).

I'm thinking about something like this:

`https://github.com/webui-project/webui`
`https://github.com/webui-project/v-webui`
`https://github.com/webui-project/nim-webui`
`https://github.com/webui-project/python-webui`
`https://github.com/webui-project/go-webui`
`https://github.com/webui-project/deno-webui`
`https://github.com/webui-project/rust-webui`

Additionally, we vote for a logo (_icon_) and move all wrapper documentation to https://webui.me/docs.
We are all already having fun coding this hobby project, but maybe it's time to do something crazier!
We should all agree on this before we move on.

**Comment by neroist** [comment]
I was thinking about that too, that would be great! Perhaps the logo could be the current favicon for <https://webui.me/>?

![webui.me favicon](https://raw.githubusercontent.com/alifcommunity/webui/main/website/favicon.ico)

**Comment by hassandraga** [comment]
![webui_240_shadow](https://github.com/alifcommunity/webui/assets/16948659/12d82216-9606-48c7-90c2-d2807b603469)

I spent hours today trying to find/design a log.
This is the perfect one. "_W_".

**Comment by hassandraga** [comment]
All those are taken.
`https://github.com/webui`
`https://github.com/webui-project`

Should we go with `https://github.com/project-webui` or something else?

**Comment by malisipi** [comment]
> ![webui_240_shadow](https://github.com/alifcommunity/webui/assets/16948659/12d82216-9606-48c7-90c2-d2807b603469)
> 
> I spent hours today trying to find/design a log.
> This is the perfect one. "_W_".

Is it not Waterfox browser logo

https://commons.m.wikimedia.org/wiki/File:Waterfox_logo_2019.png

**Comment by neroist** [comment]
+1 me too! Sounds like a good name

**Comment by hassandraga** [comment]
Welcome!
`https://github.com/webui-dev/webui` is done.
Let's create other repositories.

`https://github.com/webui-dev/v-webui`
`https://github.com/webui-dev/nim-webui`
`https://github.com/webui-dev/python-webui`
`https://github.com/webui-dev/go-webui`
`https://github.com/webui-dev/deno-webui`
`https://github.com/webui-dev/rust-webui`

**Comment by hassandraga** [comment]
> Is it not Waterfox browser logo

It seems like it is. I didn't know, honestly. I just found the "_W_" icon at https://icons8.com/.
Anyway, I tweaked it! I hope that works.

**Comment by malisipi** [comment]
@hassandraga Can i get write access for V wrapper?

**Comment by hassandraga** [comment]
All members should have the "_write_" access. Let me double check.

**Comment by malisipi** [comment]
It can be affected by branch protection rule.
![image](https://github.com/webui-dev/webui/assets/87281783/4cb3148e-850f-4e07-90ab-fbd2b0ed543f)

**Comment by AlbertShown** [comment]
I got it. Sorry, my bad. I will fix it.

**Comment by hassandraga** [comment]
@AlbertShown only organization owner can change roles.
@malisipi It seems GitHub doesn't support a way to automatically assign "Maintainer" roles to all members for all repositories. So, I created a new Team, and I assigned it to all repo with "Maintainer" roles. Should work fine now.

**Comment by malisipi** [comment]
Yes, everything is fine atm.

**Comment by AlbertShown** [comment]
@hassandraga All maintainers also can update and change the roles.

![image](https://github.com/webui-dev/webui/assets/116365846/8b16d90f-9ed1-42f5-b73c-ee2855203d9f)
