### ISSUE TITLE
Open file API

### ISSUE THREAD

**Issue by AlbertShown** [webui-dev/webui#101]
I propose adding a new WebUI JavaScript API like `webui_file()`, which makes the WebUI handle the OS APIs to show the open file dialog.

**Pros:**
- Wrappers do not need to add/use open file dialog modules

**Cons:**
- Compiling WebUI will need an extras flag like `-lcomdlg32` on Windows, and `pkg-config --cflags --libs gtk+-3.0` on Linux which make WebUI works only if GTK is installed.

**Comment by malisipi** [comment]
I think we shouldn't add thirdparty depencies. Since WebUI is a webview library, WebUI can have a dialog library based on webview popups.

**Comment by neroist** [comment]
I agree.

**Comment by hassandraga** [comment]
Seems we all agreed to not add any thirdparty depencies, and to keep WebUI portable as possible.
