### ISSUE TITLE
Vivaldi for Arch based distros

### ISSUE THREAD

**Issue by demetera** [webui-dev/webui#104]
Vivaldi binary in Arch / Manjaro distros called by `vivaldi-stable` while there's no checks for this behaviour in the code:

```
Line 2621:
if(_webui_cmd_sync(win, "vivaldi --version", false) == 0) {
```
```
Line 2623:
sprintf(win->browser_path, "vivaldi");
```

![image](https://github.com/webui-dev/webui/assets/3475944/2c3d2095-731b-44fc-8389-8a9f0e897479)

Thanks!

**Comment by hassandraga** [comment]
Thank you for reporting this. I have `vivaldi` in my Ubuntu setup, so, would you like please duplicate the line and add `vivaldi-stable`, then test it and create a PR. Otherwise, I can create a PR and you test it later in your environment.

**Comment by Dialga** [comment]
There is also `vivaldi-snapshot`, can another line be added to test for that?

**Comment by AlbertShown** [comment]
If `vivaldi-snapshot` can exist on the end-user's machine and it's not an exception, then yes. Please add a PR.

**Comment by demetera** [comment]
Thank you for merging `vivaldi-stable`
Made the same for `vivaldi-snapshot`
meanwhile unable to test at the moment

**Comment by demetera** [comment]
Thanks for merging!

I had an idea  for these kind of builds, like canary, devs, stables, snapshots, betas etc. (every chromium based browser applies though), just to add a clause on main README.md with recommendation to create something like `alias vivaldi="vivaldi-snapshot"` in bash configuration file

**Comment by AlbertShown** [comment]
Good idea. Perhaps we can just hardcode them by priority.
 Can you please create a list by priority?

**I'm thinking:**
```
vivaldi
vivaldi-stable
vivaldi-canary
vivaldi-dev
vivaldi-snapshot
vivaldi-beta
```

Then we apply all of them to all Chromium-based browsers.

**Comment by Dialga** [comment]
> Good idea. Perhaps we can just hardcode them by priority. Can you please create a list by priority?
> 
> **I'm thinking:**
> 
> ```
> vivaldi
> vivaldi-stable
> vivaldi-canary
> vivaldi-dev
> vivaldi-snapshot
> vivaldi-beta
> ```
> 
> Then we apply all of them to all Chromium-based browsers.

Brilliant, although for opera they have `opera-developer`.

**Comment by demetera** [comment]
Dears,

this is the list of binaries for Chromium based browsers, its repository and if it's AUR package - number of votes:

```
google-chrome-stable (AUR) - 2206
google-chrome-unstable (AUR) - 649

chromium (extra)
chromium-snapshot-bin (AUR) - 497
chromium-dev (AUR) - 159 - unable to install

vivaldi-stable (extra)
vivaldi-snapshot (AUR) - 128

brave (AUR) - 690
brave-browser-beta (AUR) - 39
brave-beta (AUR) - 39

opera (extra)
opera-developer (AUR) - 89

microsoft-edge-stable (AUR) - 98
microsoft-edge-dev (AUR) - 93

firefox (extra) 
firefox-nightly (AUR) - 611 - unable to install
firefox-beta-bin (AUR) - 402
firefox-beta (AUR) - 402
```

**Comment by hassandraga** [comment]
Thank you for the list. It's really helpful.
You can implement all those changes to all Chromium-based browsers in Linux.
Just please provide a list of tested and not tested ones, so I can finish the testing before merging.

**Comment by hassandraga** [comment]
Implemented. Thank you.
