### ISSUE TITLE
Frontend framework support

### ISSUE THREAD

**Issue by griffith1deady** [webui-dev/webui#109]
Hello. I am interested in this question, is there any frontend framework support planned, like in Tauri/Wails 2?

Specifically, I'm interested at least in React support. 
I tried building react to html with inline styles, but, as one would expect, there is no loading of scripts and other resources like images or fonts, and I don't know how to deal with that.

**Comment by AlbertShown** [comment]
Did you try the `serve_a_folder` example?
Please give us more details on how your app works so we can better help.

**Comment by griffith1deady** [comment]
Sorry, but I don't use this:
`setCurrentDir(currentSourcePath().parentDir() & "\out")`.
Solved the problem, thanks!
(I'm using nim binding).
I used to just write the file path as:
`e.window.show("out/biography.html"),`
and because of that it didn't load resources.
(maybe you should mark somewhere about external directories?)

**Comment by AlbertShown** [comment]
Yes, closing this issue and re-opening it in Nim-WebUI is better.

Just to clarify something, `e.window.show("out/biography.html")` means the root is `"/"`, so all resources should use the path `"out/myFile.css"`, or add to your HTML `<base href="out/" />` then resources path can be `"myFile.css"`.

**Comment by AlbertShown** [comment]
@hassandraga We should make `webui_set_root_folder()` a public API, right now it is private and no internal core code is using it.
