### ISSUE TITLE
Is it possible to compile webui for 32bit systems?

### ISSUE THREAD

**Issue by ekermer** [webui-dev/webui#116]
Hey,

first thanks for this great tool! I wanted to try some of my projects on a Raspberry today but was not able to compile it properly. Tried to change the make file so it will compile but the functions throws errors (wrong ELF class) when executing. 
Do you think it is possible to make it work, or is it too complex? (I can understand if you don't see the benefit in it, as it is such a niche case)

All best

**Comment by AlbertShown** [comment]
Thank you for your feedback. Yes, we are always here to fix and improve the WebUI project. Honestly, I don't have a Raspberry Pi to test it, but if you share with us the logs output, we can identify the issue and fix it.

1. Which language it's your project written in?
2. Are you able to compile WebUI alone?
3. Which compiler you are using?
4. Can you share the compile logs (_In case this is a compile issue_)
5. Any extra details are welcome to help us quickly know what's going on

**Comment by ekermer** [comment]
Great! When I try to build it on linux/raspberry with GCC I get the following error:
```
Build WebUI Library (GCC Release Static)...
gcc: error: unrecognized command line option ‘-m64’
make: *** [Makefile:29: release] Error 1
```
this makes sense, as the raspberry is no 64bit system.
I tried to replace the arguments, but it looks like this is not the only thing I need to change, right?

**Comment by Shad7ows** [comment]
I think this may help
Instade -m64 use -march=armv8-a, since raspberry pi use ARM cpu.

**Comment by ekermer** [comment]
Thanks, I tried this before, but it still builds wrong .dll files.
It builds the application without error, but when I try to use the function with python I get this error:
```
>>> from webui import webui
>>> MyWindow = webui.window()
webui_lib Exception: /home/pi/.local/lib/python3.7/site-packages/webui/webui-2-x64.so: wrong ELF class: ELFCLASS64
```

**Comment by AlbertShown** [comment]
The official PyPI package has a 64Bit compiled version. You need to replace the file `/home/pi/.local/lib/python3.7/site-packages/webui/webui-2-x64.so` with your 32Bit compiled one.

If you already did this, double check the compiled one if it's truly 32Bit:

Run command `file webui-2-x64.so`
32Bit -> `webui-2-x64.so: ELF 32-bit LSB shared object...`
64Bit -> `webui-2-x64.so: ELF 64-bit LSB shared object...`

**Comment by ekermer** [comment]
Ah great!
It seams to work now (at least spawning windows)! Will check tomorrow the other functionality.

**Comment by skinkairewalker** [comment]
can u share webui-2-x32.so ?

**Comment by AlbertShown** [comment]
Hey @skinkairewalker, You can easily compile your 32Bit version. Just download the [stable release](https://github.com/webui-dev/webui/releases). Then replace `-m64` with `-m32` in [Makefile](https://github.com/webui-dev/webui/blob/main/build/Linux/GCC/Makefile).

**Comment by skinkairewalker** [comment]
wow, thanks by support @AlbertShown

**Comment by skinkairewalker** [comment]
how do i define if the dlls will be x64 or x32 in the windows ' MSVC\makefile' ?

**Comment by AlbertShown** [comment]
`dumpbin /headers webui-2-x64.dll`

Will print `XXXX machine (x86)` or `XXXX machine (x64)`
