### ISSUE TITLE
Free Pascal binding for WebUI

### ISSUE THREAD

**Issue by delphius** [webui-dev/webui#117]
Hello, I made a [wrapper for webui on free pascal](https://github.com/delphius/pascal-webui), tested it, made several examples, everything works great.

Is there any point in making a separate repository here or is my existing one enough?

**Comment by hassandraga** [comment]
Hey @delphius, Thank you for creating this new wrapper. I appreciate it. You can find a newly created repo to maintain your wrapper [here](https://github.com/webui-dev/pascal-webui). I will add links to the Free Pascal wrapper in the main wrappers list and the official website when you finish updating the new repo.

**Comment by delphius** [comment]
@hassandraga, I'm finished updating the new repo.
I'm not very versed in the intricacies of the design of repositories, if anything, correct me

**Comment by AlbertShown** [comment]
Thank you very much for the implementation 👍
I will update the readme file to match the other wrapper's format soon.
