### ISSUE TITLE
Invalid .zip prebuilt binaries?

### ISSUE THREAD

**Issue by DougAnderson444** [webui-dev/webui#120]
I just tried to download the zip files from both github and the website, it says the zip file is invalid?

![image](https://github.com/webui-dev/webui/assets/6699901/25ce0e3a-1965-4090-838b-76c682596615)

**Comment by rivy** [comment]
It's a plain TAR archive mislabelled as a ZIP.
`7z` will open it, regardless of file name.

**Comment by AlbertShown** [comment]
This is surprising!

All the compressed files are created using those [scripts](https://github.com/webui-dev/webui/tree/main/build).

[Windows](https://github.com/webui-dev/webui/blob/main/build/windows_build.bat): `tar.exe -c -f %TAR_OUT% Windows\*`
[Linux](https://github.com/webui-dev/webui/blob/main/build/linux_build.sh): `tar -c -f $TAR_OUT Linux/*`
[macOS](https://github.com/webui-dev/webui/blob/main/build/macos_build.sh): `tar -c -f $TAR_OUT macOS/*`

Just damaged files on commit? Or should we update the scripts?

**Comment by GiuseppeCesarano** [comment]
I can confirm that expanding files with `tar xf` works. And yes! tars and zips are different file formats if we make the archive using tar the file extension should be changed on windows too

**Comment by rivy** [comment]
All the build scripts (linux_build.sh, macos_build.sh, and windows_build.bat) are using a variation of ...

```shell
TAR_OUT="webui-macos-x64-v$WEBUI_VERSION.zip"
cd "Release"
sleep 2
tar -c -f $TAR_OUT macOS/*
```

> https://github.com/webui-dev/webui/blob/914c988/build/linux_build.sh#L72-L75

This creates an uncompressed TAR file. And I don't see any compression anywhere in the scripts.
So, as built, they should all be named *FILE_NAME.tar* (changing the TAR_OUT extensions from '.zip' to '.tar').
