### ISSUE TITLE
Serve embedded content

### ISSUE THREAD

**Issue by petabyt** [webui-dev/webui#125]
I would like to serve embedded CSS, JS, and HTML files to the web server. From what I understand from reading the code, it's only possible to serve files from filename, and show a single page of HTML.

I think this could be solved with a simple modification to `_webui_serve_file`, where I can specify a custom file handler instead of using `webui_show`.
```
webui_file_serve_thing(blah, handler);
...
const char *handler(blah, char *filename) {
  if (!strcmp(filename, "test.html")) {
    return "Hello, World";
  }
}
```

This would allow a single binary AppImage for complex applications.

**Comment by AlbertShown** [comment]
Great idea!

**To serve one embedded HTML file:**
```c
webui_show(my_window, "<html>Hello</html>");
```

**To serve multiple embedded HTML files:**
```c
const char* MyFilesHandler(int window, const char* filename) {

    if (!strcmp(filename, "test.html"))
        return "<html>Hello</html>";
     else if (!strcmp(filename, "style.css"))
        return "body { color: #FFF }";
     else
        return NULL; // This will result to 404 file not found
}

webui_set_file_handler(my_window, MyFilesHandler);

webui_show(my_window, "test.html");
```

**Comment by AlbertShown** [comment]
Thank you @petabyt 👍
If no one sees any issue with this I'm going to implement this new feature

**Comment by petabyt** [comment]
> ```c
> const char* MyFilesHandler(int window, const char* filename) {
> 
>     if (!strcmp(filename, "test.html"))
>         return "<html>Hello</html>";
>      else if (!strcmp(filename, "style.css"))
>         return "body { color: #FFF }";
>      else
>         return NULL; // This will result to 404 file not found
> }
> 
> webui_set_file_handler(my_window, MyFilesHandler);
> 
> webui_show(my_window, "test.html");
> ```

One problem, it also has to serve data (such as images), which aren't null terminated. So maybe something like:
```
const void* MyFilesHandler(int window, const char* filename, int *length) {
...
*length = 1000;
return jpeg_image;
...
*length = 0;
return "null terminated string";
...
}
```

**Comment by AlbertShown** [comment]
I updated the serve a folder example to test this new feature:
https://github.com/webui-dev/webui/blob/0b55abff5aea6b8bd5ab4057867dbfeb447b5a75/examples/C/serve_a_folder/main.c#L51

**Comment by petabyt** [comment]
Looks good 👍 thanks!

**Comment by petabyt** [comment]
Here's an example of a standalone binary I had talked about: https://github.com/petabyt/webui-demo
Works so much better than webview. Thanks for making this lib 👍
