### ISSUE TITLE
Windows zip

### ISSUE THREAD

**Issue by NegativeIQ** [webui-dev/webui#127]
Windows Release v2.3.0 zip archive (didnt check others)  wont open with windows explorer. Opening it with 7z or WinRar works fine. At least should be noted in readme or compressed in compatibility. The main reason something stupid as these is actually an issue is because people are starting to use Windows 11 more and more, and right now Microsoft is pull all kind of shit with forcing some settings with each new update. And if you are just starting, click that download for release, and open from browser, you may not notice winrar/7z is not associated with zip files (for god knows what reason - thank you microsoft! )

**Comment by AlbertShown** [comment]
I agree that Windows 11 forces many mandatory features that make the UX horrible. On the other hand, the Zip issue is already solved https://github.com/webui-dev/webui/issues/120. But @hassandraga did not update the archive files yet.

Thank you, @NegativeIQ, for bringing this out.
