### ISSUE TITLE
Linux Installation Bug | Ubuntu 22.04

### ISSUE THREAD

**Issue by MertGunduz** [webui-dev/webui#139]
#### I was trying to build the program by using this method:

```
git clone https://github.com/webui-dev/webui.git
cd webui/build/Linux/GCC
make
```
<hr>

#### But it gave me this error:

![image](https://github.com/webui-dev/v-webui/assets/65850970/c738d417-edb2-47ed-8e1d-77939a10f5ce)

```fatal error: client/webui.h: No such file or directory```

<hr>

Is there a way to solve this problem?

Thanks,
**_Mehmet Mert_**

**Comment by MertGunduz** [comment]
![image](https://github.com/webui-dev/v-webui/assets/65850970/110d7a09-e8f7-4b31-93a0-3d69c1df55d9)

<hr>

#### Also, opened the vscode to the source directory and had this error:

```
[{
	"resource": "/home/mehmetmertgunduz/webui/src/webui.c",
	"owner": "C/C++: IntelliSense",
	"code": "1696",
	"severity": 8,
	"message": "cannot open source file \"client/webui.h\"",
	"source": "C/C++",
	"startLineNumber": 19,
	"startColumn": 1,
	"endLineNumber": 19,
	"endColumn": 26
}]
```

**Comment by AlbertShown** [comment]
This repo has a new build process that still needs to be completed. We are still voting for it.
For now, you can use the [stable released](https://github.com/webui-dev/webui/releases) version. Simply download `Source code (tar.gz)`.

**Comment by MertGunduz** [comment]
Thanks a lot @AlbertShown 🚀

**Comment by hassandraga** [comment]
Fixed, now simply clone and build. 
No dependency is needed (_Unless you want to modify `webui_bridge.ts`_)
https://github.com/webui-dev/webui/commit/096b0cf8369fe6cea30d366abbdc41de83dd36e5
