### ISSUE TITLE
web browser deprecated version ?

### ISSUE THREAD

**Issue by skinkairewalker** [webui-dev/webui#140]
Hello everyone, I'm currently making games with construct 3, I've been testing with webui c++, when I try to load this [link ](https://soqueto.com/game2/), I get the following [error](https://prnt.sc/-S-4R_GvKlau)

is there any solution for this? I would like to run in kiosk mode.

**Comment by skinkairewalker** [comment]
> What OS do you use?
Windows 10 x64

> What browser do you use? 
[Chrome](https://prnt.sc/k3bJQBJPJ1ss)

> What do you see when you open the [link](https://soqueto.com/game2/) in your regular browser?
[opens normally.](https://prnt.sc/r3PAcwxDK7Ml)

Could it be that there is some restriction on the browser?

**Comment by AlbertShown** [comment]
I guess this is why:
https://github.com/webui-dev/webui/blob/10e11da5e2f0dd2282662caa0eba531e8c2f4ec5/src/webui.c#L2825

@hassandraga, any reason why GPU is disabled?

**Comment by AlbertShown** [comment]
If you build the WebUI from the source, you can modify this line and re-compile it to use WebGL.

https://github.com/webui-dev/webui/blob/main/src/webui.c#L2825

**Comment by skinkairewalker** [comment]
I get this error when trying to compile the webui_main source :

```
Build WebUI Library (MSVC Release Static)...
NMAKE : fatal error U1077: 'cl /Zl /Fowebui.obj /c /EHsc "../../../src/webui.c" /I "../../../include" 1>NUL 2>&1' : código de retorno '0x2'
Stop.
```
