### ISSUE TITLE
Has the new_server open function been canceled?

### ISSUE THREAD

**Issue by lightcax** [webui-dev/webui#142]
`
AttributeError: 'window' object has no attribute 'new_server
`

**Comment by tobealive** [comment]
Hey @lightcax 

It appears that you refer to an outdated function that has been removed in here:
https://github.com/webui-dev/webui/commit/18d68ab586a2f521fd94d9114511a4a750dc8620

**Comment by AlbertShown** [comment]
Related https://github.com/webui-dev/python-webui/issues/1
