### ISSUE TITLE
Bug: missing bytes in big string on webui_script

### ISSUE THREAD

**Issue by JOTSR** [webui-dev/webui#145]
When using big string in WebUI script 22 bytes are missing at the end to the client response, whatever the buffer size is.
Discovered using deno_webui in [Deplot/src/deplot.ts#L174](https://github.com/JOTSR/Deplot/blob/624cfb4482b48879e5a2f04ee08f7eb792df2435/src/deplot.ts#L174).

**Comment by AlbertShown** [comment]
I will try to fix it. How big is the data?

**Comment by JOTSR** [comment]
I don't test the threshold but I see it with ~300kb

**Comment by AlbertShown** [comment]
`#define WEBUI_MAX_BUF (4096000)`
The `WEBUI_MAX_BUF` is big enough to hold 300Kb. I will investigate about this bug, Thank you for pointing this out 👍

**Comment by hassandraga** [comment]
I just test it using a 2 133 350 character script (~2133.35 Kb). And it works fine. I will test it again with bigger string tomorrow.

**Comment by hassandraga** [comment]
Is this issue related to Webui-Deno?

**Comment by hassandraga** [comment]
This issue exists in the Deno wrapper.
