### ISSUE TITLE
Bug: performance issue when launching multiple windows simultaneously

### ISSUE THREAD

**Issue by JOTSR** [webui-dev/webui#146]
When trying to launch multple windows almost simultaneously and awating isShown to use webui_run/webui_script, server crash most of the time. To solve this issue, the actual trick is to wait 1.5s (the same time as js bridge max connection timeout before close) before calling client side code.

**Comment by AlbertShown** [comment]
I noticed that a while ago, I discovered that running the browser, starting the HTTP server and WebSocket server, running the bridge and connecting back to the webui server... all take a few seconds. In my Go-lang project, I fix it too by simply not running multiple windows so quickly.

Please keep this issue open until I fix it in the webui core.

**Comment by hassandraga** [comment]
Working on this. Thank you for the report.

**Comment by hassandraga** [comment]
Increasing the max dynamic mem
Adding mutex in critical threads
https://github.com/webui-dev/webui/commit/78da533a3a98c59ab819c865256576a4f9d8db3a

Running a quick test, always working:

![image](https://github.com/webui-dev/webui/assets/16948659/fa8d4d3d-7463-4dc1-b02d-679533074b89)
