### ISSUE TITLE
how to not allow the display of links to appear?

### ISSUE THREAD

**Issue by skinkairewalker** [webui-dev/webui#147]
How do I never display the destination both OnMouseHover and Loading the page?
[display of links ](https://prnt.sc/cOdyvaMMW830)

**Comment by tobealive** [comment]
Afaik this can't be done using an anchor tag. After all it's a web browser that is used. A solution that comes to my mind is to use e.g. a span element with a data-ref attribute and JS to trigger that on click event. Or maybe buttons depending on what you want to achieve.

**Comment by AlbertShown** [comment]
I guess you can achieve that by removing the `href`, and adding an `OnClick="your_js_here"`.
In the end, as @tobealive said, this is a web browser, so all UI management is done by HTML5/CSS3/JS.

**Comment by skinkairewalker** [comment]
thanks :D
