### ISSUE TITLE
Configurable root address? (For use with proxy paths)

### ISSUE THREAD

**Issue by sfeister** [webui-dev/webui#159]
Normally, something like "/theme.css" needs to come from "https://localhost:{port}/theme.css".

In some cases, like when using a proxy through JupyterHub, that same resource will instead need to come from "https://{myproxyaddress}/{port}/theme.css".

The app doesn't know that, so links are hardcoded, e.g. as "https://localhost:{port}/theme.css", which results in failure to get the resource.

You may be familiar with Dask --- in that case what we can do is configure Dask so it knows the proxy path to the Dask dashboard is:

```
dask.config.config["distributed"]["dashboard"]["link"] = "https://{myproxyaddress}/{port}/status"
```

(See the [yaml configuration of "link" example from Dask](https://docs.dask.org/en/latest/configuration.html#yaml-files))

If the developers could enable a similar configurable base address for WebUI, that would be helpful for this use case of proxies!

**Comment by sfeister** [comment]
This issue was submitted by mistake to the wrong repository

**Comment by AlbertShown** [comment]
Thank you for report this @sfeister, I guess we can easily add this feature to webui. So, I'm re-opening this issue.

**Comment by hassandraga** [comment]
Need more investigation.

**Comment by hassandraga** [comment]
Indeed, This issue is not related to WebUI. Any request other than `localhost:{port}` will not reach WebUI in the first place.
