### ISSUE TITLE
Example for submitting binary data from golang to WebUI JavaScript?

### ISSUE THREAD

**Issue by AlbertShown** [webui-dev/webui#161]
New feature request https://github.com/webui-dev/webui/discussions/160

**Comment by hassandraga** [comment]
Added `webui_send_raw()`.

**Comment by AlbertShown** [comment]
Thank you for adding this feature that fast. Projects that need to send binary data to UI will need to send it back to the app (backend), So please, when you have free time, we need `send_raw()` in JavaScript.

**Comment by hassandraga** [comment]
Added https://github.com/webui-dev/webui/commit/e941e35fc62bc7b5f5af8372fb80757ab152f3cd
Now simply `webui.call('MyID', new Uint8Array([0x41, 0x42, 0x43]))`

**Comment by alecstein** [comment]
I'm looking for documentation on how to use `webui_send_raw()` (I'm coming from the zig side of things.) I checked the repo for code or examples and don't see anything. That's alright, just kind of wondering what the status of this is. I'm dealing with the same issues as the other users -- I'd like to do some plots, which requires streaming tons of data to the UI, and I'm not sure how I can currently achieve that.
