### ISSUE TITLE
WebUI not working when using latest git head

### ISSUE THREAD

**Issue by ttytm** [webui-dev/webui#162]
Calling C/C++ functions form JS does not work.

When trying to run the `call_c_from_js`/`call_cpp_from_js` examples, the functions should print their results to the terminal, but they do not. 

Checking the browser console, the error is:
```
Uncaught ReferenceError: webui_fn is not defined
    at HTMLButtonElement.onclick ((index):22:58)
```

The examples work checking out version 2.3.0
```
git checkout tags/2.3.0
```

I think it's a high priority to fix this before releasing another version.

**Comment by ttytm** [comment]
It looks like it stopped working after #131

**Comment by hassandraga** [comment]
`webui_fn()` is now `webui.call()` suggested by @JOTSR . It's a break change. But it's a small deal as this is our only JS API.

_Examples updated (https://github.com/webui-dev/webui/commit/3133bcb92a252c098f4ea39aa1131aa6d41484d9).
Website update (https://webui.me/docs/2.4.0/#/)_
