### ISSUE TITLE
webui_event_t has new element (Wrappers Update Needed)

### ISSUE THREAD

**Issue by hassandraga** [webui-dev/webui#171]
To make sending raw binary data between backend and frontend possible, I had to add a new element to `webui_event_t`.

```c
typedef struct webui_event_t {
    ...
    long long int size;
} webui_event_t;
```

Please keep this issue open until all wrappers get updated.

**Comment by ttytm** [comment]
I can offer to also have an eye on the V repository. If it's not to intrusive to extend the merge rights for my role to the V WebUI repository I would push the things like such new features or simple fixes directly, without the overhead for you. More profound changes only approved.

**Comment by delphius** [comment]
I will try to update pascal wraper to library version 2.4.0 in the very near future.

Also, a cursory glance at the header file did not find the added webui_set_hide function, while it is already implemented in the library itself.

**Comment by ttytm** [comment]
https://github.com/webui-dev/webui/blob/0d400644d13740990aeb9dc813655cd02d140be9/include/webui.h#L212

**Comment by delphius** [comment]
> because it knows how to hide

I looked at the wrong place :)

**Comment by delphius** [comment]
> I will try to update pascal wraper to library version 2.4.0 in the very near future.
> 
> ~Also, a cursory glance at the header file did not find the added webui_set_hide function, while it is already implemented in the library itself.~

Added to Pascal
