### ISSUE TITLE
Set custom browser data path

### ISSUE THREAD

**Issue by fibodevy** [webui-dev/webui#193]
All browser data is saved to HOME or USERPROFILE -> .WebUI. Currently 2 different WebUI apps share the same folder and the same settings - window size, position and possibly saved form data and passwords (didn't check that). It would be a nice feature to have the ability to set custom profile path.

**Comment by hassandraga** [comment]
Yeah, good idea, This will probably require a new API:
`webui_set_profile(const char* profileName, const char* profilePath)`

**Comment by hassandraga** [comment]
Implemented https://github.com/webui-dev/webui/commit/a616991ca679f0646bf35d580443e101369273ce.

To set your custom profile:

```c
webui_set_profile(
    myWindow, 
    "Bar", // Your profile name, usually needed for Firefox
    "/Home/Foo/Bar" // Your profile folder, usually needed for Chrome
);
```

To simply let WebUI use the user default profile:
```c
webui_set_profile(myWindow, "", "");
```
