### ISSUE TITLE
Windows TCC examples don't build

### ISSUE THREAD

**Issue by ttytm** [webui-dev/webui#198]
E.g. trying to compile the minimal C example:

- When compiling the example with the WebUI library TCC compiled:
  ```
  tcc: error: undefined symbol 'strtoll'
  tcc: error: undefined symbol 'SleepConditionVariableCS'
  tcc: error: undefined symbol 'opendir'
  tcc: error: undefined symbol 'closedir'
  tcc: error: undefined symbol 'strtoull'
  tcc: error: undefined symbol 'IsWow64Process'
  ```

- GCC compiled library:
  ```
  tcc: error: invalid object file
  tcc: error: library 'webui-2-static' not found
  mingw32-make: *** [Makefile:27: release] Error 1
  ```

The errors are similar when trying to use tcc with V.
If they can be fixed, it might help to get tcc running over there.

---

Edit:
Checking out earlier stable tags like 2.3.0, the TCC example doesn't build as well. 

With 2.3.0 we run into less errors

```
tcc: error: undefined symbol 'opendir'
tcc: error: undefined symbol 'closedir'
tcc: error: undefined symbol 'IsWow64Process'
```

And checking over at `civetweb` it's related to what author is stating here: https://github.com/civetweb/civetweb/issues/1158#issuecomment-1546845523

Maybe we should remove TCC from the supported list and the examples until it works?

**Comment by hassandraga** [comment]
All those issues are related to missing header files. I suggest removing the TCC support from WebUI.
At the end of the day, any user can add headers files to TCC and compile the lib and examples.
