### ISSUE TITLE
Firefox `Uncaught ReferenceError: webui is not defined` 

### ISSUE THREAD

**Issue by ttytm** [webui-dev/webui#206]
It seems not possible to use WebUI with firefox atm.

The initial error when with the `call_c_from_js` example is
```
Uncaught TypeError: MutationObserver.observe: Argument 1 is not an object.
```
![Screenshot_20230913_065741](https://github.com/webui-dev/webui/assets/34311583/3d7b08dd-4548-447f-855e-e02420cd41b4)

After calling one of the C functions
```
Uncaught ReferenceError: webui is not defined
```
![Screenshot_20230913_065746](https://github.com/webui-dev/webui/assets/34311583/47493cc6-6fd3-4338-a600-96f5aeb3fdba)

**Comment by hassandraga** [comment]
The WebUI Bridge object issue is fixed, and the window look also get fixed.
Thank you for the report 👍
