### ISSUE TITLE
disable window resize ??

### ISSUE THREAD

**Issue by skinkairewalker** [webui-dev/webui#209]
Hello everyone, is there any way to disable the resizing of the webui window?

**Comment by AlbertShown** [comment]
I guess not. The `window` is not an `object` in your application, but it's a web browser. But you can try some JavaScript to disable the resizing of the window probbaly.

**Comment by malisipi** [comment]
There're a little tricky way to do it

```javascript
window.allow_height = 480;
window.allow_width = 640;

window.resizeTo(window.allow_width, window.allow_height);
window.addEventListener("resize", ()=>{
    if(window.outerHeight==window.allow_height && window.outerWidth==allow_width) return;
    window.resizeTo(window.allow_width, window.allow_height);
});
```
