### ISSUE TITLE
Browser Request: Gnome Web (aka Epiphany)

### ISSUE THREAD

**Issue by malisipi** [webui-dev/webui#220]
Epiphany is a browser that based on WebKit technology used by Safari.

And it supports PWAs.

![image](https://github.com/webui-dev/webui/assets/87281783/410bfffa-274e-4dea-90db-f923ab190c3b)

So, it should be able to open websites in pwa mode. I'm not sure how possible make it with automatically however it should be a way to do it.

**Comment by hassandraga** [comment]
**Epiphany web browser**
Read-only mirror: https://github.com/GNOME/epiphany
Source code: https://gitlab.gnome.org/GNOME/epiphany

I suggest not supporting it as it has fewer users. Instead, we should support Safari.

**Comment by hassandraga** [comment]
In other hand, after we fully support Safari, if Epiphany use the exact same CLI as Safari, then nothing stops us from supporting Epiphany.

**Comment by malisipi** [comment]
Since i'm not a mac user, i'm not sure about that however i guess Epiphany has different approach on application system. So it can not be ported from Safari.

Also, I agree with Epiphany support shouldn't be ordered before Safari or another bigger browser. However in my free time, i can try to add experimental support. It won't be so hard since have built-in support for PWA.

**Comment by hassandraga** [comment]
Sorry, I wasn't clear enough. Yes, I am okay with any PR to support any web browser. I prefer spending my time dealing with major web browsers. But yeah, we welcome any PR for other web browsers 👍
