### ISSUE TITLE
`chromium_options[]` and `custom_profile`

### ISSUE THREAD

**Issue by fibodevy** [webui-dev/webui#240]
If a custom profile is set, chromium options are not applied, causing Chrome to offer a translation.

```C
        if (!win->custom_profile) {
            for (int i = 0; i < (int)(sizeof(chromium_options) / sizeof(chromium_options[0])); i++) {
                c += sprintf(buffer + c, " %s", chromium_options[i]);
            }
        }
```

It should check if default profile is used (the __real__ one), not if `!win->custom_profile`

**Comment by hassandraga** [comment]
Thank you for the report. Now `webui_set_profile(myWin, "", "")` will show the correct WebUI window style using the default local profile.

**Comment by fibodevy** [comment]
Fixed
