### ISSUE TITLE
Does every new window listen on a new port?

### ISSUE THREAD

**Issue by jinzhongjia** [webui-dev/webui#290]
Does every new window listen on a new port?
And the new window uses the new port to establish a new websocket connection?
If so, is the cost a bit too much?

**Comment by fibodevy** [comment]
The port is random, only one client (window) can be connected at the same time to a single WebUI app instance

**Comment by jinzhongjia** [comment]
> The port is random, only one client (window) can be connected at the same time to a single WebUI app instance

yes, when we open two windows( two clients), that means `webui` listens two ports, right?

**Comment by jinzhongjia** [comment]
> You mean 2 applications which is 2 servers and 2 browser windows? Then yes

Yes, that's what it means. This cost is a little high?

**Comment by fibodevy** [comment]
This is the only way it can be done. Only one app can listen on one specific port.

Cost is not high at all. Many applications communicate using TCP/IP as interprocess communication in the background.

**Comment by jinzhongjia** [comment]
whether it is possible to have only one server, corresponding to multiple clients

**Comment by jinzhongjia** [comment]
ok

**Comment by jinzhongjia** [comment]
> Good question @jinzhongjia. The issue is if a window continually exchange large data it may effect other windows communication when using one single server.
> 
> Another issue when using one single server is many window specific options/features will become global options for all windows instead of window specific. For example allow a window to be accessible from the public network, or setting the root folder.
> 
> As @fibodevy said, this is the only way to do it, unless someone find another design.

I get it, thanks for your answer.
