### ISSUE TITLE
Question: how to set full screen display at startup？

### ISSUE THREAD

**Issue by zzdoreen** [webui-dev/webui#324]
hello . I want to know Is there any way to set full screen display on startup?

I‘m using C programing language

**Comment by fibodevy** [comment]
Hello

> I‘m using C programing language

It doesn't matter. WebUI doesn't provide any method to run the application in full screen and doesn't control the window itself. You have to manipulate the window using Java Script (moving, resizing). For full screen it would be:

```js
var body = document.getElementsByTagName('body')[0];
body.requestFullscreen();
```

**Comment by zzdoreen** [comment]
> ```js
> var body = document.getElementsByTagName('body')[0];
> body.requestFullscreen();
> ```

But, this function requires user interaction before it can be executed, otherwise an exception will be reported.
`Permissions check failed`

**Comment by fibodevy** [comment]
Unfortunately. Maybe simulating a click on the window would be a workaround. Or display some kind of splash window for user to click, then enter full screen mode? Until browsers provide command line options to skip such permission issues we have to use hackish workarounds.

**Comment by zzdoreen** [comment]
thanks reply

**Comment by jinzhongjia** [comment]
Do you mean exclusive full screen?

**Comment by jinzhongjia** [comment]
see this: https://github.com/webui-dev/webui/blob/2a5f0c98fbb267a5aed921a8678f3f108bb12a6e/include/webui.h#L231C19-L231C34

**Comment by fibodevy** [comment]
Oh right, I completely forgot about Kiosk mode

**Comment by zzdoreen** [comment]
> see this: https://github.com/webui-dev/webui/blob/2a5f0c98fbb267a5aed921a8678f3f108bb12a6e/include/webui.h#L231C19-L231C34请参见：https://github.com/webui-dev/webui/blob/2a5f0c98fbb267a5aed921a8678f3f108bb12a6e/include/webui.h#L231C19-L231C34

Yes ! thank you!!!!!!
