### ISSUE TITLE
help: is there a way to hide console/cmd ?

### ISSUE THREAD

**Issue by jimying** [webui-dev/webui#328]
as title

I know it's very helpful show console/cmd for debug, but i want to hide it when release.

**Comment by jinzhongjia** [comment]
> Probably default should be release, while for debugging, users can add `debug` argument in CLI. Just a suggestion.

This build option is part of `build.zig`, it is decided by the user, it should not be provided by the package, and as an imported package, it is theoretically impossible to modify the settings of the package that imports it.

**Comment by jinzhongjia** [comment]
But we can put it in the zig-webui readme as tips.
