### ISSUE TITLE
How to make only the the server running? (Do not create browser window)

### ISSUE THREAD

**Issue by bin-san** [webui-dev/webui#330]
How can I make a webserver using webui, without using the native window? I mean the program will run the server locally, then I have to access it via web browser. I dont want to create native window... Is it possible?

**Comment by bin-san** [comment]
I am using C++. Can you tell me what to do?

**Comment by bin-san** [comment]
```
#include <webui.hpp>

int main() {

    webui::window myWindow;
    myWindow.show_browser(
    	"<html><script src=\"webui.js\"></script> Hello World from C++! </html>", 
    	NoBrowser);
    webui::wait();
    return 0;
}
```
But now How can I know which port it is running on?

**Comment by fibodevy** [comment]
Use `webui_get_url()`, it returns HOST:PORT.

```C
 myWindow.get_url();
```

**Comment by bin-san** [comment]
Thank you.
