### ISSUE TITLE
`.mjs` files are responded with `text/plain` rather than `text/javascript`

### ISSUE THREAD

**Issue by sitd2813** [webui-dev/webui#335]
**On**: deno-webui 2.4.4 (webui 2.4.2)
**Setup**: `index.html` with `<script type="module" src="main.mjs"></script>` as entry point

`.mjs` is a common filename extension for a JavaScript module file along with `.js`. However, WebUI does not seem to recognize this. If I use `main.js`, it works, but `main.mjs` doesn't.

### Error message

```text
Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/plain". Strict MIME type checking is enforced for module scripts per HTML spec.
```

**Comment by jinzhongjia** [comment]
Indeed this is a problem, maybe we can open an additional API later to specify mime
