### ISSUE TITLE
Edge Browser window won't show up when running as SYSTEM account in Windows

### ISSUE THREAD

**Issue by capthehacker99** [webui-dev/webui#348]
Simply run the minimal example, then run as system account using gsudo -s, the browser window won't pop up but the console is still blocking.

**Comment by capthehacker99** [comment]
I ran msedge.exe in SYSTEM account and it doesn't show up. I guess this is an Edge problem.

**Comment by neroist** [comment]
Closed as this is not an issue with WebUI.
