### ISSUE TITLE
SvelteKit + webui problem

### ISSUE THREAD

**Issue by sensiblearts** [webui-dev/webui#392]
There may be a conflict between how a `SvelteKit` SPA boots itself and how `zig-webui` app loads its content. To see this, do the following.

Create a `SvelteKit` project with
```
npm create svelte@latest webui-sveltekit
```

Choose:
- "Skeleton" app option
- "No" do not use TypeScript, nor JSDoc
- Add "ESLint"

Follow instructions to test it, ending with `npm run dev`.

Next, set it up to generate an SPA:

```
npm install @sveltejs/adapter-static
```

Edit `svelte.config.js` to look like this:

```javascript
// import adapter from '@sveltejs/adapter-auto';
import adapterStatic from '@sveltejs/adapter-static';

/** @type {import('@sveltejs/kit').Config} */

const config = {
    kit: {
        // adapter-auto only supports some environments, see https://kit.svelte.dev/docs/adapter-auto for a list.
        // If your environment is not supported, or you settled on a specific environment, switch out the adapter.
        // See https://kit.svelte.dev/docs/adapters for more information about adapters.
        // adapter: adapter()

        adapter: adapterStatic({
            pages: 'build',
            assets: 'build',
            fallback: 'app.html', // required to generate app.html in build folder
            precompress: false,
            strict: false
        })
    }
};

export default config;
```

In the `/routes` folder, add a file, `+layout.js` and add this:

```javascript
export const ssr = false;
export const prerender = false;
```

Run `npm run dev` to test.

The above project is available at [https://github.com/sensiblearts/SvelteKit-WebUI-SPA-test.git](https://github.com/sensiblearts/SvelteKit-WebUI-SPA-test.git)

To build the SPA:

`npm run build`

Copy the `build` folder (I renamed it `spa_build`) and all of its contents (app.html, compiled JS, etc) into a new `zig-webui` test project, at the same level as its `src` folder.  

Edit `main.zig` to read as follows:

```C
pub fn main() !void {
    var nwin = webui.newWindow();

	const path = "./spa_build";
    const filename = "app.html";

    _ = webui.setDefaultRootFolder(path);

    _ = nwin.show(filename);

    webui.wait();
}
```

Run the program with
`zig build run` and you will see this:

![Screenshot zig webui](https://github.com/webui-dev/webui/assets/805314/2a75874f-7ee2-47b3-b4b2-5e38cd57993f)

Then, right-click on the screen to inspect the JS console:

![Screenshot JS console](https://github.com/webui-dev/webui/assets/805314/4e3fca99-bbca-4222-86d0-5ac235ab031e)

In the above screenshot, the line `app.html:28.11` is pointing to this:

```javascript
kit.start(app, element);
```

Thus, it's the entry point to a SvelteKit app that is causing the problem. If you drill down on the first module listed in the Not found error, you see this:

![Screenshot JS compiled](https://github.com/webui-dev/webui/assets/805314/a63e7387-9dd9-42e9-8cf9-f7a69e837c76)

Which, to me, looks like the first thing a SvelteKit app does is replace the client-side state -- I think they call this "hydration" -- and to do this it seems to be *reloading itself* -- looking for app.html for a second load. But it cannot find it...?

**Note:** The above happens *without* including `webui.js` in the app. If  we add `<script src="webui.js"></script>` to `app.html`, we get the same 404, but the app crashes and reloads repeatedly, with this cycling in the console:

![Screenshot webui websocket](https://github.com/webui-dev/webui/assets/805314/ae29c56c-569c-4726-b496-9946664d8d73)

I think that someone who knows the internals of WebUI should talk to someone who knows the internals of SvelteKit.

**Comment by ttytm** [comment]
To showcase usage of webui with sveltekit I published a mini-app this week is. https://github.com/ttytm/gsysmo. It doesn't have a lot of features but the concept of using SK also applies with zig-webui. Maybe the reference can be of tiny help.

> I created a simple app for the purpose of having an example. It uses Go-WebUI and uses with Bun and SvelteKit (Svelte 5). Feature- and design-wise, it is an infant. Though the focus is on providing a simple example that is hopefully easy to understand.
[...]
I'm planning to keep one branch simple, without complicating things, just adding some concise notes that might help to point out some of the concepts on how this stack works together for the app. The goal is to show what is needed for a fully bundled executable in a simple way. Another branch is planned to add some real features to the application, which will be beyond an example.
Ref.: https://github.com/webui-dev/webui/issues/124#issuecomment-2143666423

Unfortunately, atm. I cannot make the time to give free individualized support. I will try to look into it soon if you can't resolve it or get better help than this.

**Comment by sensiblearts** [comment]
Thank you @ttytm . I'm gone for a couple of days. When I get back I'll figure out what's different with your Go/SvelteKit5 app vs my Zig/SvelteKit4 app. 

The only difference I see from my phone is that you set root folder to "build" whereas mine is set to "./spa_build" (dot slash).

**Comment by ttytm** [comment]
@sensiblearts skimmed over the repo. It seems there is no `<script src="webui.js"></script>` added anywhere (Note: this is a virtual file, you just need this line of code, not an actual file).

Putting it in `app.html` would be one way. 

```html
<! -- app.html -->
...
	<meta name="viewport" content="width=device-width, initial-scale=1" />
	<script src="webui.js"></script>
	%sveltekit.head%
...
```


Though I add it in `÷layout.svelte`:
```svelte
<! -- +layout.svelte -->
<svelte:head>
	<script src="webui.js"></script>
</svelte:head>
```

Having it there allows for some flexibility. E.g., you can make the import conditional and work  on parts of the frontend like on a regular website in a regular browser (plain `npm run dev`, or `bun run dev` and opening the localhost instance).
```svelte
<! -- +layout.svelte -->
<svelte:head>
	{#if process.env.NODE_ENV === 'production'}
		<script src="webui.js"></script>
	{/if}
</svelte:head>
```

Depending on what you work on this might allow for a faster way to develop the frontend.
To also have an example for this exact case, there is something in `+page.svelte`. It loads mockdata instead getting the systemdata from the backend.
```svelte
<! -- +page.svelte -->
...
onMount(async () => {
	if (process.env.NODE_ENV !== 'production') {
		// Alternatively, create a try condition: `try { webui; } catch { ... }`
		// to check whether `webui` is available.
		console.log('Using dummy data in development environment');
		const mockdata = await import('$lib/dev/mockdata');
		data = mockdata.data;
		setInterval(async () => {
			data.processes = mockdata.randomizeProcs();
			data.cpu_used_percent = Math.random() * 30;
			data.memory.used_percent = Math.random() * 30;
		}, 1000);
		return;
	}

	// Build environment, where webui is available.
	data = JSON.parse(await webui.getStats());
	setInterval(async () => {
		data = JSON.parse(await webui.getStats());
		data.processes.sort((a: Process, b: Process) => b.cpu_used_percent - a.cpu_used_percent);
	}, 1000);
});
```

Last things to mention that might be interesting to you are in the `main.go` file:

Example of opening the WebUI Window when you already run the website-like development frontend (like described above).
```go
// Example that connects to a running localhost instance during development.
w.Show("<html><script src='webui.js'></script></html>")
w.Navigate("http://localhost:5173")
```
For the regular app I'm eventually building the frontend into a static site and use:
```go
// Opening the statically build site
ui.SetDefaultRootFolder("ui/build")
w.ShowBrowser("index.html", ui.ChromiumBased)
```

So there are some more small differences that make the big impact :D.

**Comment by sensiblearts** [comment]
@hassandraga thank you. I'm not sure how to proceed with a PR, or what you would like me to do next.

**Comment by sensiblearts** [comment]
Duh, sorry. I just realized it's a *committed* PR. Thanks.

**Comment by ttytm** [comment]
@sensiblearts sorry about the miss on your note about the `<script`. Went to fast into the code of the repo and missing that part of the message.

> sorry for my ignorance of GitHub workflows, but I am guessing that the "nightly build" of zig-webui will integrate the nightly build of webui and the PR you just committed? So I should try it tomorrow?

Yep if not tinkering with a local clone of zig-webui, as soon as the dependency is bumped. @jinzhongjia keeps it up to date with the current development build.

**Comment by jinzhongjia** [comment]
@sensiblearts I will test this later

**Comment by jinzhongjia** [comment]
> This PR ([0462ca7](https://github.com/webui-dev/webui/commit/0462ca7fdb4a868449fa682bc39681110f8c5951)) should fix the WS close warning for now.此 PR ( 0462ca7 ) 现在应该修复 WS 关闭警告。

I just briefly tested it, the problem looks like it still exists,

**Comment by sensiblearts** [comment]
@hassandraga , @ttytm , @jinzhongjia -- I think this is **not** a Zig vs. Go problem, it may be a Linux vs Windows problem for webui.js.

I just installed Go and [gcc](https://jmeubank.github.io/tdm-gcc/), then, per [https://github.com/webui-dev/go-webui](https://github.com/webui-dev/go-webui),
- built the c-go stuff with Powershell `(irm https://raw.githubusercontent.com/webui-dev/go-webui/main/setup.ps1 | iex`
- `go build` and saw that it made the webui library folder with dll etc
- then, back in @ttytm 's [gsysmo project](https://github.com/ttytm/gsysmo), `go run main.go`

... and I get the **same behavior** as before, but with more info about what's crashing it -- **webui.js line 605**:

![image](https://github.com/webui-dev/webui/assets/805314/89d3c9cf-38e0-4d9f-b949-aa4dedae7585)

**Comment by sensiblearts** [comment]
@hassandraga the event bind call that you suggests also fixes the infinite reload in zig-webui for me:

```Zig
pub fn main() !void {
    var nwin = webui.newWindow();
    _ = nwin.bind("", events);   // Added
    const path = "./src/build";
    _ = webui.setDefaultRootFolder(path);
    _ = nwin.showBrowser(".html", webui.Browsers.ChromiumBased);
    webui.wait();
}

fn events(_: webui.Event) void {
    {}
}
```

There remains one initial `Error: Not found: /index.html` but it disappears quickly and the SvelteKit app runs normally. I suspect that this too will be fixed when the latest `webui.js` build makes its way into `zig-webui`.

Thank you!

**Comment by sensiblearts** [comment]
The _infinite_ page reload has been fixed, but with `zig-webui` I'm still getting _one single_ reload happening due to the steps you discovered:
1. Svelte start kit.start
2. Svelte update history history.replaceState
3. WebUI catch it, and (_even if there is a call to bind all_) -- WebUI (apparently) reloads the page using URL of history.replaceState.

In other words, `_ = nwin.bind("", events);` catches all history.replaceState events _except the very first one_.

So, I'm looking through the TypeScript and wondering: Would it make sense to connect to the backend ***after*** the event listeners are connected?

For example, instead of this:

```TypeScript
               // Connect to the backend application
		this.#start();
		// Handle navigation server side
		if ('navigation' in globalThis) {
			globalThis.navigation.addEventListener('navigate', (event) => {
//...
                }
```
Do something like this:

```TypeScript
		// Handle navigation server side
		if ('navigation' in globalThis) {
			globalThis.navigation.addEventListener('navigate', (event) => {
//...
                }
               // Connect to the backend application
		this.#start();
```
### ?

**Comment by sensiblearts** [comment]
Thank you for the instructions. I'll let you know.

**Comment by sensiblearts** [comment]
I turned off server navigation in the bridge constructor:
```
#allowNavigation = true;
```
and I stopped binding events in my zig project,
```
   // _ = nwin.bind("", events);

```
And the app runs without any infinite reload but still has the weird, single 404 in the SvelteKit code at app load:

![image](https://github.com/webui-dev/webui/assets/805314/b1e05355-d05a-4cfb-9134-9d06f1792a0e)

The exact same compiled SvelteKit app runs fine when served with npm serve (when no webui.js is added).

**Comment by sensiblearts** [comment]
I used `mingw32-make debug` and it produced debug libs but I did not make progress on that. I'll try again later.

However, I found a workaround. Here it is, and then a comment about why I think it works:

```Zig
pub fn main() !void {
    const path = "./src/build";

    const file_content =
        \\ <!doctype html>
        \\ <html lang="en">
        \\ 	<head>
        \\ 		<meta charset="utf-8" />
        \\ 		<link rel="icon" href="/favicon.png" />
        \\ 		<meta name="viewport" content="width=device-width, initial-scale=1" />
        \\ 		<script src="webui.js"></script>
        \\ 		<link rel="modulepreload" href="/_app/immutable/entry/start.BTHfqu-a.js">
        \\ 		<link rel="modulepreload" href="/_app/immutable/chunks/entry.DfSPpY9w.js">
        \\ 		<link rel="modulepreload" href="/_app/immutable/chunks/scheduler.-OmmOMvn.js">
        \\ 		<link rel="modulepreload" href="/_app/immutable/chunks/index.Dr1V4utH.js">
        \\ 		<link rel="modulepreload" href="/_app/immutable/chunks/control.CYgJF_JY.js">
        \\ 		<link rel="modulepreload" href="/_app/immutable/entry/app.BEvzDeO2.js">
        \\ 		<link rel="modulepreload" href="/_app/immutable/chunks/preload-helper.BQ24v_F8.js">
        \\ 		<link rel="modulepreload" href="/_app/immutable/chunks/index.CA6owI4p.js">
        \\ 	</head>
        \\ 	<body data-sveltekit-preload-data="hover"; class="overflow-hidden">
        \\ 		<div style="display: contents;">
        \\ 			<script>
        \\ 				{
        \\ 					__sveltekit_dajdg0 = {
        \\ 						base: ""
        \\ 					};
        \\ 					const element = document.currentScript.parentElement;
        \\ 					Promise.all([
        \\ 						import("/_app/immutable/entry/start.BTHfqu-a.js"),
        \\ 						import("/_app/immutable/entry/app.BEvzDeO2.js")
        \\ 					]).then(([kit, app]) => {
        \\ 						kit.start(app, element);
        \\ 					});
        \\ 				}
        \\ 			</script>
        \\ 		</div>
        \\ 	</body>
        \\ </html>
    ;

    var nwin = webui.newWindow();

    _ = nwin.bind("", events);

    _ = webui.setDefaultRootFolder(path);

    _ = nwin.show(file_content);

    // _ = nwin.showBrowser(file_content, webui.Browsers.Chromium);
    // only seems to work with content as filename, not content as html string.

    webui.wait();
}

fn events(_: webui.Event) void {
    {}
}
```

**Why I think it works**: 
The error in the last screenshot shows that the SvelteKit app is already loaded (js chunk "app...") but then tries to reload / refresh index.html. Why is it doing that? My guess is that webui is telling the browser to load it -- but it's already been loaded.

I guessed that webui would have no need to send a reload message to the browser if it was initialized with an html string. Maybe the guess was correct.

**FYI**, the adapter settings in `svelte.config.js`:

```TypeScript
kit: {
			adapter: process.env.ADAPTER === 'static'
			? adapterStatic({
				pages: 'build',
				assets: 'build',
				fallback: 'index.html', // needed to generate index.html, because prerender == false
				precompress: false,
				strict: false,
			})
			: adapterNode(),

	}
```

@hassandraga I can close this if you're ready.

**Comment by sensiblearts** [comment]
My pleasure. I've decided to go with `webui` instead of Tauri.

Thank you.
