### ISSUE TITLE
Using zig cc

### ISSUE THREAD

**Issue by wwderw** [webui-dev/webui#445]
I don't know if this is another skill issue on my end or related to zig cc or webui.  I'm using c as my backend language, but attempted to use zig cc as my compiler to also have cross compile abilities.

Using `make CC="zig cc -target x86_64-linux-musl"` everything works just as it should.  I'm able to use zig cc to build my project against musl no problem.

However, when I try `make CC="zig cc -target x86_64-windows-gnu"` it outputs a lot of errors related linker errors with civetweb.  Is there something else that I should be doing when trying to cross compile on windows, is this related to zig or does something else needed to be handled with webui?

**Comment by jinzhongjia** [comment]
Both webui and zig-webui provide `build.zig`. If you want to use them for cross-compilation, just use `zig build examples -Dtarget=x86_64-windows-gnu`，this will compile x86 64 bits windows' exe with GNU C

**Comment by jinzhongjia** [comment]
make will execute the makefile prepared for Linux and Macos, which lacks linking some libs required by Windows, so theoretically it cannot be compiled.

**Comment by wwderw** [comment]
Yea, straight zig build still gives me the error on Ole32, which I think is also what it was complaining about using make as well.  It seems to work on the host system, but not when cross compiling.

**Comment by jinzhongjia** [comment]
Because the lib should be ole32 on linux, not Ole32

**Comment by jinzhongjia** [comment]
Windows is not case sensitive when linking libraries

**Comment by jinzhongjia** [comment]
You can temporarily use the zig-webui build library, which is the same as webui.

**Comment by wwderw** [comment]
I noticed the main branch was updated as well, it appears to be working there now.  I managed to get that and the zig-webui working as well.  I may try out the wrapper, I've been meaning to learn more zig (I can't mentally handle Rust, zig seems to make more sense to me), but still in the baby steps phase.

Thanks for the help!!!
