### ISSUE TITLE
Strange Behavior

### ISSUE THREAD

**Issue by wwderw** [webui-dev/webui#447]
Anybody notice browsers losing the connection to webui?  I have tried on Chromium, Firefox, I even tried the official binaries for 2.4.2 and they all still lose connection.  This is on Arch and on Linux Mint, both sets of browsers on both distros (just in case it was the Arch install needing some love).

I would like to think my skills aren't that lacking, but I just don't know why it also affects the older stable build as well, so I'm wondering if something went on with the latest versions of those browsers.

Thoughts?

**Comment by jinzhongjia** [comment]
Mine is archlinux, using the main branch, everything is normal

**Comment by wwderw** [comment]
![minExample](https://github.com/webui-dev/webui/assets/24878362/6f8ae281-3e7f-4f84-aac9-ea50091aeb13)

That's what I would get with the minimal example using the current main branch and using 2.4.2 official archive files after it would be connected for maybe 20-30 seconds.   I have used it with zig build and regular gcc as well.

**Comment by wwderw** [comment]
I used an application that I was working on, with known working links to open up new windows and file handling and the file handling was not displaying properly, nor would it actually open windows when buttons were pressed.  So even if I am wanting to get the server from timing out, it seems to be blocked.  Really strange.

[log.txt](https://github.com/user-attachments/files/16136488/log.txt)

**Comment by wwderw** [comment]
![consoleLog](https://github.com/webui-dev/webui/assets/24878362/08a0c9c0-c864-4849-8d4f-8f1f6c879a67)

**Comment by wwderw** [comment]
No.  It turns out that I had an id="webui" attribute and I changed it and boom it worked.
