### ISSUE TITLE
problem with <a download= ...></a>

### ISSUE THREAD

**Issue by sensiblearts** [webui-dev/webui#479]
I have a SvelteKit SPA (front end only) that works well in dev mode and after a build/compiles.

It has a link to download an image file (this html is compiled from Svelte components); the key point is the **download** attribute:

```html
<a href="/api/images/userdb-12345/imag:12345" tabindex="0" class="inline-flex ..." download="testfile.jpg" data-button-root="">
    click to download
</a>
```
The image is being retrieved from a route (/api/...) served by a nodeJS backend.

For the Svelte SPA (in dev mode or after a build), clicking the link in the browser triggers a download of the image file, as expected: 
1. I can see a log in the nodeJS API that the image was fetched
2. It downloads the file

However, when the exact same SPA is embedded / being shown by WebUI, it fails:
1. The nodeJS API is never called
2. I can see in my `zig-webui` logging that two bound events are detected: MOUSE_CLICK, and NAVIGATION.
3. No file download happens

Any ideas what's wrong?  All other image and API features work fine.

Related: Is there a `webui` setting that will enable the web tools (inspect, JS console, etc)?  (I feel like i did this before.., or maybe that was tauri dev, can't remember)

Thanks.

**Comment by sensiblearts** [comment]
Thank you for your patience and help, @AlbertShown -- how did I not know that :-)

FYI, my use of webui (.show() a SPA served by nodeJS), or perhaps just the binding of webui to all events,  is somehow preventing the browser from doing a download normally triggered by the `<a download= />` attribute. (My intuition says that using webui is somehow making the browser think it's a cross origin request, so is ignoring it.)

But I'm leaving this issue closed because, in my opinion, for a desktop app, using the `fileSave` method of the [File System Access API](https://github.com/GoogleChromeLabs/browser-fs-access) is more what users will expect: a native file save dialog to place the file where they wish. On the desktop, it's really a "save as" or an "export," not a "download," from the users perspective.

**Comment by bminer** [comment]
ChatGPT says:

> Yes, the download attribute of an anchor (<a>) tag can work with WebView2, but it requires some considerations based on how WebView2 handles downloads. By default, WebView2 will try to open the file linked in the anchor tag rather than downloading it.
>
> When the download attribute is present, it indicates to the browser that the linked resource should be downloaded instead of navigating to it. However, in WebView2, the download behavior for links with the download attribute may need to be handled explicitly.
>
> WebView2 provides an event, DownloadStarting, that allows you to manage file downloads. If you are using the download attribute on an anchor tag, you might still need to intercept the download event in your WebView2 control to specify where the file should be saved.

The solution as suggested is using the [File System Access API](https://developer.mozilla.org/en-US/docs/Web/API/File_System_API). Here's an example:

```js
const handle = await showSaveFilePicker({
	suggestedName: "text.json",
	types: [],
})
const stream = await handle.createWritable()
await stream.write(blob)
await stream.close()
```

It should be noted that the File System API is **not** supported by Firefox or Safari.
