### ISSUE TITLE
ThreadSanitizer data race inside webui_show_browser

### ISSUE THREAD

**Issue by Lev275568** [webui-dev/webui#518]
revision d5b25ca1a827d3ec07be9607232edb0c27172918

```
void sandbox()
{
    size_t handle = webui_new_window();
    assert(handle != 0);
    assert(webui_set_root_folder(handle, "/home/user2"));
    webui_show_browser(handle, "unknownFile_ieshoi3G.html", Chromium);
    std::abort();
}
```

> 
> WARNING: ThreadSanitizer: data race (pid=154801)
>   Read of size 4 at 0x7ffff4427028 by thread T1:
>     #0 master_thread_run /webui/src/src/civetweb/civetweb.c:20466:9 (test+0x1910956) 
>     #1 master_thread /webui/src/src/civetweb/civetweb.c:20593:2 (test+0x18f5402) 
> 
>   Previous write of size 4 at 0x7ffff4427028 by main thread:
>     #0 mg_stop /webui/src/src/civetweb/civetweb.c:20722:2 (test+0x18f1cff) 
>     #1 _webui_socket_test_listen_mg /webui/src/src/webui.c:4088:5 (test+0x18da4b6) 
>     #2 _webui_port_is_used /webui/src/src/webui.c:4106:10 (test+0x18d8cf5) 
>     #3 _webui_get_free_port /webui/src/src/webui.c:7423:17 (test+0x18d8bd2) 
>     #4 _webui_show_window /webui/src/src/webui.c:7005:56 (test+0x18dac29) 
>     #5 _webui_show /webui/src/src/webui.c:6728:16 (test+0x18d8317) 
>     #6 webui_show_browser /webui/src/src/webui.c:1673:12 (test+0x18d8121) 
> 
>   Location is heap block of size 165368 at 0x7ffff4427000 allocated by main thread:
>     #0 calloc /compiler-rt/lib/tsan/rtl/tsan_interceptors_posix.cpp:686:5 (test+0x82687b) 
>     #1 mg_calloc /webui/src/src/civetweb/civetweb.c:1497:9 (test+0x18ee9a5) 
>     #2 mg_start2 /webui/src/src/civetweb/civetweb.c:20979:29 (test+0x18f231a) 
>     #3 mg_start /webui/src/src/civetweb/civetweb.c:21700:9 (test+0x18f5489) 
>     #4 _webui_socket_test_listen_mg /webui/src/src/webui.c:4078:16 (test+0x18da487) 
>     #5 _webui_port_is_used /webui/src/src/webui.c:4106:10 (test+0x18d8cf5) 
>     #6 _webui_get_free_port /webui/src/src/webui.c:7423:17 (test+0x18d8bd2) 
>     #7 _webui_show_window /webui/src/src/webui.c:7005:56 (test+0x18dac29) 
>     #8 _webui_show /webui/src/src/webui.c:6728:16 (test+0x18d8317) 
>     #9 webui_show_browser /webui/src/src/webui.c:1673:12 (test+0x18d8121) 
> 
>   Thread T1 'civetweb-master' (tid=154804, running) created by main thread at:
>     #0 pthread_create /compiler-rt/lib/tsan/rtl/tsan_interceptors_posix.cpp:1023:3 (test+0x828161) 
>     #1 mg_start_thread_with_id /webui/src/src/civetweb/civetweb.c:5829:11 (test+0x18f5335) 
>     #2 mg_start2 /webui/src/src/civetweb/civetweb.c:21683:2 (test+0x18f3f69) 
>     #3 mg_start /webui/src/src/civetweb/civetweb.c:21700:9 (test+0x18f5489) 
>     #4 _webui_socket_test_listen_mg /webui/src/src/webui.c:4078:16 (test+0x18da487) 
>     #5 _webui_port_is_used /webui/src/src/webui.c:4106:10 (test+0x18d8cf5) 
>     #6 _webui_get_free_port /webui/src/src/webui.c:7423:17 (test+0x18d8bd2) 
>     #7 _webui_show_window /webui/src/src/webui.c:7005:56 (test+0x18dac29) 
>     #8 _webui_show /webui/src/src/webui.c:6728:16 (test+0x18d8317) 
>     #9 webui_show_browser /webui/src/src/webui.c:1673:12 (test+0x18d8121) 
> 
> SUMMARY: ThreadSanitizer: data race /webui/src/src/civetweb/civetweb.c:20466:9 in master_thread_run
> 
>

**Comment by mith101** [comment]
The data race warning is still an issue. From what I understand, the issue got fixed in civetweb, but you didn't update to the fixed version in here in webui.

**Comment by AlbertShown** [comment]
@mith101 Thank you for letting us know, I will update it soon.

**Comment by AlbertShown** [comment]
Done https://github.com/webui-dev/webui/commit/f93b5a680c3c285d0d601081686347f7df4d0bc5
