### ISSUE TITLE
Open webui with default browser if it's supported

### ISSUE THREAD

**Issue by malisipi** [webui-dev/webui#81]
If default browser is supported, webui should prefer it to respect user preferences, get fastest loading time (the browser will already be in RAM).

You can get the browser path from `HKEY_CLASSES_ROOT\htmlfile\shell\open\command` for Windows
Source: https://superuser.com/a/1111131

Also you can check the default browser with `BROWSER` environment variable in Linux.
Source: https://askubuntu.com/a/16626

**Comment by AlbertShown** [comment]
WebUI should use a web browser's order based on which is best for UX (_User Experience_). Some browsers are terrible in app mode, while others are good. Please see [this list](https://github.com/alifcommunity/webui/issues/59#issuecomment-1487576620) for more information.

[WebUI v2.2.0](https://github.com/alifcommunity/webui/tree/WebUI_v2.2.0) is not complete yet, but the user can use `webui_show_browser()` to choose the web browser to be used.

**Comment by malisipi** [comment]
Increasing the time is solving the issue however waiting the user for awhile (30 second or more) is not good option. Starting new process of the already working browser is not best option however it can solve the issue.

**Comment by AlbertShown** [comment]
We can increase it to 30 seconds for now, but that does not mean every time the user starts the program, he should wait 30 seconds. But it means WebUI waits until the browser starts for a maximum of 30 seconds.

Additionally, we can add what you suggested because it makes more sense. For example, if the default browser is `Edge`, why should WebUI use `Chrome`?! It should use `Edge`, as it's probably already running, which makes WebUI apps start faster.

You are totally right. We will implement your suggestion 👍

**Comment by mohamedke** [comment]
you can use this fonction for change the time
webui_set_timeout

https://github.com/alifcommunity/webui/blob/527d000b45fadf5fa5f81682a9816573abbc3e1b/src/webui.c#L719

**Comment by AlbertShown** [comment]
True, but increasing the default one is better, so WebUI apps will run fine in slow environments (_Slow Old PCs, Slow Virtual Machines_).
https://github.com/alifcommunity/webui/blob/527d000b45fadf5fa5f81682a9816573abbc3e1b/src/webui_core.h#L28

I already implemented the Win32 version of your suggestion of finding the running web browser. I got good results. Your idea was excellent!, I'm working on the Linux version now...

**Comment by AlbertShown** [comment]
`webui_set_timeout()` is an additional option for the programmer to modify `WEBUI_DEF_TIMEOUT`.

**Comment by AlbertShown** [comment]
https://github.com/alifcommunity/webui/commit/3a0cd4968f7c39d0204c5bb8ab6bd9aaef806343

**Comment by hassandraga** [comment]
Windows & Linux implementation is done.
Still need macOS implementation to be done.

**Comment by AlbertShown** [comment]
Already been implemented for Windows, Linux and macOS in WebUI v2.3.0.

https://github.com/webui-dev/webui/blob/e955ee22282cf43f56fd278503cfbae2dfda8c42/src/webui.c#L3515
