### ISSUE TITLE
Why the need for a non-permissive license?

### ISSUE THREAD

**Issue by xD0135** [webui-dev/webui#89]
Comparing with other projects (Tauri, Wails, Fyne) that aim to provide similar goals of using Web technologies as the GUI for desktop (and upcoming mobile) and use a permissive license, why the need to use a non-permissive license on this project? I believe this hampers the wide adoption of the project, specially when considering options for commercially releasing products that are closed-source.

**Comment by malisipi** [comment]
The library uses a GPLv2 licensed library. So the exact license must be GPLv2.

**Comment by AlbertShown** [comment]
To replace Mongoose, we should find a library that has all the features:

1. Supports the latest WebSockets standards
2. Support encrypted TLS communication in WebSockets
3. Has a web server feature

_The closest Mongoose WebSocket competitor I found is [libwebsockets.org](https://libwebsockets.org/), but if we used it, we still need another lib for the web server._

**Comment by AlbertShown** [comment]
> CivetWeb is based on the [Mongoose project](https://github.com/cesanta/mongoose).

> and CiwetWeb was created by Thomas Davis (sunsetbrew) as "the MIT fork of mongoose".

> Although CivetWeb is a fork from Mongoose from 2013, the code bases are different now...

Wonderful! This is what we need! I will give it a try 👍

**Comment by AlbertShown** [comment]
Seems Civetweb will provide WebUI with better server features + TLS WebSocket. That's enough to switch. Thank you @xD0135 for pointing this out.

**Comment by hassandraga** [comment]
> WebUI v2.3.0
> * License changed from `GPLv2` to 'MIT'. Thanks to @xD0135
> * The core APIs is completely changed from `Mongoose` to `civetweb`. Thanks to @xD0135

Thank you @xD0135
