### ISSUE TITLE
TCC is not supported on Windows

### ISSUE THREAD

**Issue by malisipi** [webui-dev/webui#99]
> builder error: 'tlhelp32.h' not found

This is because https://github.com/civetweb/civetweb/issues/1158
https://github.com/malisipi/vwebui/issues/21

**Comment by hassandraga** [comment]
TCC does not have `'tlhelp32.h`. It needs to be manually added to the TCC default include folder.
While https://github.com/civetweb/civetweb/issues/1158 is another different issue that needs to be fixed by the Civetweb team.
